module ALU (
    input  wire [7:0] alu_inA,          
    input  wire [7:0] alu_inB,          
    input  wire [2:0] alu_control_in,

    output reg  [3:0] flag_reg_out, // [overflow, carry, sign, zero] 
    output reg  [7:0] alu_result_out
);

    always @(*) begin
        flag_reg_out = 4'b0000;

        case (alu_control_in)
            3'b000: begin         // This control is generated by following instructions: ADD, LDR, STR, ADDI
                {flag_reg_out[2], alu_result_out} = alu_inA + alu_inB; 
                flag_reg_out[3]                   = (~alu_inA[7] & ~alu_inB[7] & alu_result_out[7]) | 
                                                    (alu_inA[7] & alu_inB[7] & ~alu_result_out[7]);
            end
            
            3'b001: begin         // This control is generated by following instructions: SUB, SUBI
                {flag_reg_out[2], alu_result_out} = alu_inA - alu_inB;
                flag_reg_out[3]                   = (~alu_inA[7] & alu_inB[7] & alu_result_out[7]) | 
                                                    (alu_inA[7] & ~alu_inB[7] & ~alu_result_out[7]);
            end
            
            3'b010: alu_result_out = alu_inA & alu_inB;       // AND
            3'b011: alu_result_out = alu_inA | alu_inB;       // OR
            3'b100: alu_result_out = alu_inA ^ alu_inB;       // XOR
            3'b101: alu_result_out = ~(alu_inA | alu_inB);    // NOR

            3'b110: alu_result_out = alu_inA << alu_inB[2:0]; // LSL 
            3'b111: alu_result_out = alu_inA >> alu_inB[2:0]; // LSR

            default: alu_result_out = 8'b00000000;
        endcase

        flag_reg_out[0]   = (alu_result_out == 8'b00000000);
        flag_reg_out[1]   = alu_result_out[7];
    end

endmodule